/**
 * HTML and Markdown templates for brainstorm output.
 */

// ---------------------------------------------------------------------------
// HTML template
// ---------------------------------------------------------------------------

export const BRAINSTORM_HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{title}} — Brainstorm Spec</title>
  <style>
    :root {
      --bg: #1a1b26; --fg: #c0caf5; --accent: #7aa2f7;
      --border: #3b4261; --card: #24283b; --muted: #565f89;
      --green: #9ece6a; --yellow: #e0af68; --red: #f7768e;
      --purple: #bb9af7;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; background: var(--bg); color: var(--fg); line-height: 1.6; }
    .container { max-width: 960px; margin: 0 auto; padding: 2rem; }
    h1 { color: var(--accent); font-size: 1.8rem; margin-bottom: 0.5rem; }
    h2 { color: var(--purple); font-size: 1.3rem; margin: 2rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; }
    h3 { color: var(--fg); font-size: 1.1rem; margin: 1.2rem 0 0.5rem; }
    .subtitle { color: var(--muted); margin-bottom: 2rem; }
    .stats { display: flex; gap: 1.5rem; flex-wrap: wrap; margin: 1rem 0; }
    .stat { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 0.75rem 1.25rem; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: var(--accent); }
    .stat-label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
    .badge-must { background: rgba(247,118,142,0.15); color: var(--red); }
    .badge-should { background: rgba(224,175,104,0.15); color: var(--yellow); }
    .badge-could { background: rgba(158,206,106,0.15); color: var(--green); }
    .badge-functional { background: rgba(122,162,247,0.15); color: var(--accent); }
    .badge-nonfunctional { background: rgba(187,154,247,0.15); color: var(--purple); }
    .badge-constraint { background: rgba(224,175,104,0.15); color: var(--yellow); }
    .req-card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; margin: 0.75rem 0; }
    .req-statement { font-weight: 500; margin-bottom: 0.5rem; }
    .req-meta { font-size: 0.85rem; color: var(--muted); }
    .criteria-list { margin: 0.5rem 0; padding-left: 1.5rem; }
    .criteria-list li { margin: 0.25rem 0; font-size: 0.9rem; }
    .theme-section { margin: 1.5rem 0; }
    .idea-item { padding: 0.4rem 0; font-size: 0.9rem; border-bottom: 1px solid var(--border); }
    .idea-status { font-size: 0.75rem; font-weight: 600; }
    .idea-status.promoted { color: var(--green); }
    .idea-status.accepted { color: var(--accent); }
    .idea-status.parked { color: var(--yellow); }
    .idea-status.rejected { color: var(--red); }
    .idea-status.merged { color: var(--purple); }
    .trace-table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.85rem; }
    .trace-table th, .trace-table td { padding: 0.5rem; border: 1px solid var(--border); text-align: left; }
    .trace-table th { background: var(--card); color: var(--muted); text-transform: uppercase; font-size: 0.75rem; }
    .revision-log { font-size: 0.85rem; color: var(--muted); }
    .revision-log li { margin: 0.3rem 0; }
  </style>
</head>
<body>
<div class="container">
  <h1>{{title}}</h1>
  <p class="subtitle">Brainstorm Specification — Generated by insrc</p>

  {{stats}}

  <h2>Problem Statement</h2>
  {{problem}}

  {{themes_section}}

  {{requirements_section}}

  {{traceability}}

  {{parked_ideas}}

  {{revision_log}}

  {{session_stats}}
</div>
</body>
</html>`;

// ---------------------------------------------------------------------------
// Markdown template
// ---------------------------------------------------------------------------

export const BRAINSTORM_MD_TEMPLATE = `# {{title}}

*Brainstorm Specification — Generated by insrc*

{{stats}}

## Problem Statement

{{problem}}

{{themes_section}}

{{requirements_section}}

{{traceability}}

{{parked_ideas}}

{{revision_log}}

{{session_stats}}`;
